/** World units: 1 unit ≈ 1 meter */

export const WORLD = {
  size: 80,
  half: 40,
};

export const BUILDINGS = [
  {
    id: 'cafe',
    name: 'Cozy Cafe',
    x: -18,
    z: -8,
    w: 6,
    d: 5,
    h: 4.2,
    color: '#8B5A2B',
    roof: '#5C3317',
    emoji: '☕',
    action: 'Buy Coffee',
    activity: 'cafe',
  },
  {
    id: 'shop',
    name: 'General Store',
    x: 20,
    z: 4,
    w: 7,
    d: 6,
    h: 4.5,
    color: '#E85D5D',
    roof: '#9B2C2C',
    emoji: '🏪',
    action: 'Browse Shop',
    activity: 'shop',
  },
  {
    id: 'park',
    name: 'Central Park',
    x: 0,
    z: -22,
    w: 14,
    d: 10,
    h: 0.4,
    color: '#3D9B6E',
    roof: '#2E7D4F',
    emoji: '🌳',
    action: 'Relax',
    activity: 'park',
    flat: true,
  },
  {
    id: 'townhall',
    name: 'Town Hall',
    x: 2,
    z: 12,
    w: 9,
    d: 7,
    h: 6,
    color: '#5BA3C9',
    roof: '#2C6B8A',
    emoji: '🏛️',
    action: 'View Quests',
    activity: 'townhall',
  },
  {
    id: 'dock',
    name: 'Fishing Dock',
    x: -28,
    z: 22,
    w: 8,
    d: 4,
    h: 1.2,
    color: '#6B8E9F',
    roof: '#4A6570',
    emoji: '🎣',
    action: 'Fish',
    activity: 'fish',
    flat: true,
  },
  {
    id: 'forest',
    name: 'Dark Forest',
    x: 26,
    z: -22,
    w: 10,
    d: 10,
    h: 0.3,
    color: '#1F5C2E',
    roof: '#163F20',
    emoji: '🌲',
    action: 'Chop Wood',
    activity: 'chop',
    flat: true,
  },
  {
    id: 'mine',
    name: 'Crystal Mine',
    x: 28,
    z: 24,
    w: 7,
    d: 6,
    h: 3.5,
    color: '#6B6B7A',
    roof: '#3F3F4A',
    emoji: '⛏️',
    action: 'Mine Ore',
    activity: 'mine',
  },
];

export const NPCS = [
  {
    id: 1,
    name: 'Mayor Jenkins',
    x: 4,
    z: 8,
    emoji: '👨‍💼',
    color: '#F5D76E',
    dialogue: "Welcome to Cozy Town! Complete quests at Town Hall to earn rewards.",
  },
  {
    id: 2,
    name: 'Cafe Owner Luna',
    x: -16,
    z: -6,
    emoji: '👩‍🍳',
    color: '#F8B4C4',
    dialogue: 'Fresh coffee restores energy. Come by anytime!',
  },
  {
    id: 3,
    name: 'Shop Keeper Sam',
    x: 18,
    z: 2,
    emoji: '🛍️',
    color: '#A8E6CF',
    dialogue: 'I stock tools and snacks. Spend those hard-earned coins!',
  },
  {
    id: 4,
    name: 'Fisher Bob',
    x: -26,
    z: 20,
    emoji: '🎣',
    color: '#8EC5E8',
    dialogue: 'The fish are biting near the dock. Cast a line!',
  },
  {
    id: 5,
    name: 'Woodcutter Alice',
    x: 24,
    z: -20,
    emoji: '🪓',
    color: '#C4A484',
    dialogue: 'Need lumber? The forest always has more trees.',
  },
];

export const QUESTS = [
  {
    id: 'first-steps',
    title: 'First Steps',
    description: 'Visit the Town Hall',
    reward: { coins: 50, xp: 20 },
    completeOn: 'townhall',
  },
  {
    id: 'coffee-break',
    title: 'Coffee Break',
    description: 'Buy coffee at the cafe',
    reward: { coins: 30, xp: 15 },
    completeOn: 'cafe',
  },
  {
    id: 'fishing-trip',
    title: 'Fishing Trip',
    description: 'Catch a fish at the dock',
    reward: { coins: 100, xp: 50 },
    completeOn: 'fish',
  },
  {
    id: 'lumberjack',
    title: 'Lumberjack',
    description: 'Chop wood in the Dark Forest',
    reward: { coins: 60, xp: 30 },
    completeOn: 'chop',
  },
  {
    id: 'deep-delve',
    title: 'Deep Delve',
    description: 'Mine ore at Crystal Mine',
    reward: { coins: 80, xp: 40 },
    completeOn: 'mine',
  },
];

export const SHOP_ITEMS = [
  { id: 'bait', name: 'Fishing Bait', emoji: '🪱', price: 15, desc: 'Slightly better fishing luck' },
  { id: 'axe', name: 'Sturdy Axe', emoji: '🪓', price: 40, desc: 'A trusty woodcutting tool' },
  { id: 'pick', name: 'Iron Pick', emoji: '⛏️', price: 50, desc: 'Mine faster… spiritually' },
  { id: 'snack', name: 'Trail Mix', emoji: '🥜', price: 12, desc: 'Restores 15 energy' },
  { id: 'hat', name: 'Cozy Cap', emoji: '🧢', price: 75, desc: 'Looking good in town' },
];

export const ACTIVITIES = {
  fish: {
    xp: 15,
    coins: 25,
    energy: -10,
    message: 'You caught a fish! 🐟',
    item: { id: 'fish', name: 'Fresh Fish', emoji: '🐟' },
  },
  chop: {
    xp: 12,
    coins: 20,
    energy: -8,
    message: 'You chopped some wood! 🪵',
    item: { id: 'wood', name: 'Oak Wood', emoji: '🪵' },
  },
  mine: {
    xp: 18,
    coins: 30,
    energy: -12,
    message: 'You found some ore! 💎',
    item: { id: 'ore', name: 'Crystal Ore', emoji: '💎' },
  },
  cafe: {
    xp: 5,
    coins: -10,
    energy: 25,
    message: 'You enjoyed a coffee! ☕',
    item: null,
  },
  park: {
    xp: 3,
    coins: 0,
    energy: 8,
    message: 'You relax in the peaceful park. 🌳',
    item: null,
  },
};

export const AVATARS = ['😊', '😎', '🧑‍🔧', '👩‍🌾', '🧔', '🧒', '🦊', '🐱', '🐸', '🦉'];

export const INTERACT_RANGE = 5.5;
