/** World units: 1 unit ≈ 1 meter */

export const WORLD = {
  size: 80,
  half: 40,
};

export const BUILDINGS = [
  {
    id: 'cafe',
    name: 'Cozy Cafe',
    x: -18,
    z: -8,
    w: 6,
    d: 5,
    h: 4.2,
    color: '#8B5A2B',
    roof: '#5C3317',
    emoji: '☕',
    action: 'Buy Coffee',
    activity: 'cafe',
  },
  {
    id: 'shop',
    name: 'General Store',
    x: 20,
    z: 4,
    w: 7,
    d: 6,
    h: 4.5,
    color: '#E85D5D',
    roof: '#9B2C2C',
    emoji: '🏪',
    action: 'Browse Shop',
    activity: 'shop',
  },
  {
    id: 'park',
    name: 'Central Park',
    x: 0,
    z: -22,
    w: 14,
    d: 10,
    h: 0.4,
    color: '#3D9B6E',
    roof: '#2E7D4F',
    emoji: '🌳',
    action: 'Relax',
    activity: 'park',
    flat: true,
  },
  {
    id: 'townhall',
    name: 'Town Hall',
    x: 2,
    z: 12,
    w: 9,
    d: 7,
    h: 6,
    color: '#5BA3C9',
    roof: '#2C6B8A',
    emoji: '🏛️',
    action: 'View Quests',
    activity: 'townhall',
  },
  {
    id: 'dock',
    name: 'Fishing Dock',
    x: -28,
    z: 22,
    w: 8,
    d: 4,
    h: 1.2,
    color: '#6B8E9F',
    roof: '#4A6570',
    emoji: '🎣',
    action: 'Fish',
    activity: 'fish',
    flat: true,
  },
  {
    id: 'forest',
    name: 'Dark Forest',
    x: 26,
    z: -22,
    w: 10,
    d: 10,
    h: 0.3,
    color: '#1F5C2E',
    roof: '#163F20',
    emoji: '🌲',
    action: 'Chop Wood',
    activity: 'chop',
    flat: true,
  },
  {
    id: 'mine',
    name: 'Crystal Mine',
    x: 28,
    z: 24,
    w: 7,
    d: 6,
    h: 3.5,
    color: '#6B6B7A',
    roof: '#3F3F4A',
    emoji: '⛏️',
    action: 'Mine Ore',
    activity: 'mine',
  },
  {
    id: 'plumbhq',
    name: 'Pipeworks HQ',
    x: -12,
    z: 18,
    w: 8,
    d: 6,
    h: 4.8,
    color: '#4A6FA5',
    roof: '#2C4060',
    emoji: '🔧',
    action: 'Visit Crew',
    activity: 'plumbhq',
  },
];

/** Town locals + the Greek plumber crew */
export const NPCS = [
  {
    id: 1,
    name: 'Mayor Jenkins',
    x: 4,
    z: 8,
    emoji: '👨‍💼',
    color: '#F5D76E',
    role: 'mayor',
    action: 'Talk',
    dialogue: "Welcome to Cozy Town! The plumber crew keeps our pipes flowing — go say hi at Pipeworks HQ!",
  },
  {
    id: 2,
    name: 'Cafe Owner Luna',
    x: -16,
    z: -6,
    emoji: '👩‍🍳',
    color: '#F8B4C4',
    role: 'cafe',
    action: 'Talk',
    dialogue: 'Fresh coffee restores energy. The sink was dripping until Sofia fixed it!',
  },
  {
    id: 3,
    name: 'Shop Keeper Sam',
    x: 18,
    z: 2,
    emoji: '🛍️',
    color: '#A8E6CF',
    role: 'shop',
    action: 'Talk',
    dialogue: 'I stock tools, snacks… and for fun, blasters and grenades. Don’t tell the mayor.',
  },
  {
    id: 4,
    name: 'Fisher Bob',
    x: -26,
    z: 20,
    emoji: '🎣',
    color: '#8EC5E8',
    role: 'fisher',
    action: 'Talk',
    dialogue: 'The fish are biting today! Watch the dock pipes — Dimitri patched one last week.',
  },
  {
    id: 5,
    name: 'Woodcutter Alice',
    x: 24,
    z: -20,
    emoji: '🪓',
    color: '#C4A484',
    role: 'wood',
    action: 'Talk',
    dialogue: 'Need lumber? The forest always has more trees. Tell Nico I said hi!',
  },
  // —— Plumber crew (roam around town near their posts) ——
  {
    id: 10,
    name: 'Nico “The Wrench”',
    x: -10,
    z: 16,
    emoji: '🧑‍🔧',
    color: '#5B8DEF',
    role: 'plumber',
    title: 'Crew Boss',
    roamRadius: 14,
    walkSpeed: 1.7,
    action: 'Talk',
    dialogue:
      'Kalimera! I’m Nico, boss of the plumber crew. Fix the leaking pipes around town — talk to the crew and use Fix Pipe at the leaks!',
    dialogues: [
      'Kalimera! I’m Nico, boss of the plumber crew.',
      'Leaks pop up near the fountain, cafe, dock, and HQ. Fix them for coins!',
      'Need firepower? Sam sells a Plumber Blaster and Wrench Grenades. Pure chaos. Pure fun.',
      'A good plumber listens to the pipes… and never loses their wrench.',
      'I walk the whole town checking pressure — catch me when you can!',
    ],
  },
  {
    id: 11,
    name: 'Yiannis',
    x: 3,
    z: 1,
    emoji: '🧔',
    color: '#7EB6FF',
    role: 'plumber',
    title: 'Pipe Whisperer',
    roamRadius: 9,
    walkSpeed: 1.4,
    action: 'Talk',
    dialogue: 'This fountain spring is a drama queen. Stand close to the leak and hit Fix Pipe!',
    dialogues: [
      'Yiannis here — I talk to pipes. They talk back.',
      'Fountain leak is right here. Fix it before the park becomes a pool!',
      'Pressure is poetry. Also, don’t grenade the main valve. Please.',
      'I patrol the square — if you miss me, wait by the fountain.',
    ],
  },
  {
    id: 12,
    name: 'Sofia',
    x: -14,
    z: -10,
    emoji: '👩‍🔧',
    color: '#FF9ECD',
    role: 'plumber',
    title: 'Junior Ace',
    roamRadius: 10,
    walkSpeed: 2.0,
    action: 'Talk',
    dialogue: 'Sofia! Cafe pipes are my beat. Grab a wrench energy and fix the leak by the kitchen wall.',
    dialogues: [
      'Hey! Sofia — junior ace of the crew.',
      'Cafe leak is behind Luna’s place. Fix Pipe when you’re close!',
      'Coffee + plumbing = the Cozy Town dream.',
      'I’m usually jogging between the cafe and HQ — wave if you see me!',
    ],
  },
  {
    id: 13,
    name: 'Dimitri',
    x: -26,
    z: 18,
    emoji: '🔧',
    color: '#FFB347',
    role: 'plumber',
    title: 'Dock Specialist',
    roamRadius: 8,
    walkSpeed: 1.5,
    action: 'Talk',
    dialogue: 'Dimitri at your service! Dock pipes freeze, crack, then party. Fix the leak on the pier.',
    dialogues: [
      'Dimitri — dock pipes, storms, and snacks.',
      'Pier leak is right by the water. One Fix Pipe and we’re golden.',
      'Between you and me, the blaster is great for “persuading” stubborn valves. Wink.',
      'I stick near the waterfront. Salt air is good for the soul.',
    ],
  },
  {
    id: 14,
    name: 'Elena',
    x: -8,
    z: 20,
    emoji: '😎',
    color: '#C3A6FF',
    role: 'plumber',
    title: 'Demo & Drama',
    roamRadius: 12,
    walkSpeed: 1.85,
    action: 'Talk',
    dialogue: 'Elena. I handle “controlled demolitions”… I mean pressure releases. Wrench Grenades go boom, pipes go calm.',
    dialogues: [
      'Elena — demo specialist. Mostly jokes. Mostly.',
      'HQ side leak needs a hero. Fix Pipe, then maybe toss a grenade at a rock for fun.',
      'Look around with right-drag or the look stick. You’ll see my handiwork everywhere.',
      'If I’m walking, I’m thinking. If I’m running, something exploded. Probably fine.',
    ],
  },
];

/** Interactable leaking pipes */
export const PIPE_LEAKS = [
  {
    id: 'leak-fountain',
    name: 'Fountain Leak',
    x: 1.5,
    z: -1.5,
    emoji: '💧',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Yiannis is watching this one',
  },
  {
    id: 'leak-cafe',
    name: 'Cafe Pipe Leak',
    x: -15,
    z: -11,
    emoji: '🚰',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Sofia’s job site',
  },
  {
    id: 'leak-dock',
    name: 'Dock Pipe Crack',
    x: -24,
    z: 20,
    emoji: '💦',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Dimitri’s specialty',
  },
  {
    id: 'leak-hq',
    name: 'HQ Pressure Valve',
    x: -9,
    z: 21,
    emoji: '🔧',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Elena left tools here',
  },
];

export const QUESTS = [
  {
    id: 'first-steps',
    title: 'First Steps',
    description: 'Visit the Town Hall',
    reward: { coins: 50, xp: 20 },
    completeOn: 'townhall',
  },
  {
    id: 'coffee-break',
    title: 'Coffee Break',
    description: 'Buy coffee at the cafe',
    reward: { coins: 30, xp: 15 },
    completeOn: 'cafe',
  },
  {
    id: 'fishing-trip',
    title: 'Fishing Trip',
    description: 'Catch a fish at the dock',
    reward: { coins: 100, xp: 50 },
    completeOn: 'fish',
  },
  {
    id: 'lumberjack',
    title: 'Lumberjack',
    description: 'Chop wood in the Dark Forest',
    reward: { coins: 60, xp: 30 },
    completeOn: 'chop',
  },
  {
    id: 'deep-delve',
    title: 'Deep Delve',
    description: 'Mine ore at Crystal Mine',
    reward: { coins: 80, xp: 40 },
    completeOn: 'mine',
  },
  {
    id: 'meet-crew',
    title: 'Meet the Crew',
    description: 'Talk to Nico at Pipeworks HQ',
    reward: { coins: 40, xp: 25 },
    completeOn: 'talk-nico',
  },
  {
    id: 'pipe-rookie',
    title: 'Pipe Rookie',
    description: 'Fix any leaking pipe',
    reward: { coins: 70, xp: 35 },
    completeOn: 'fixpipe',
  },
  {
    id: 'master-plumber',
    title: 'Master Plumber',
    description: 'Fix 4 leaks around town',
    reward: { coins: 200, xp: 100 },
    completeOn: 'fixpipe-all',
  },
];

export const SHOP_ITEMS = [
  { id: 'bait', name: 'Fishing Bait', emoji: '🪱', price: 15, desc: 'Slightly better fishing luck' },
  { id: 'axe', name: 'Sturdy Axe', emoji: '🪓', price: 40, desc: 'A trusty woodcutting tool' },
  { id: 'pick', name: 'Iron Pick', emoji: '⛏️', price: 50, desc: 'Mine faster… spiritually' },
  { id: 'snack', name: 'Trail Mix', emoji: '🥜', price: 12, desc: 'Restores 15 energy' },
  { id: 'hat', name: 'Cozy Cap', emoji: '🧢', price: 75, desc: 'Looking good in town' },
  { id: 'wrench', name: 'Golden Wrench', emoji: '🔧', price: 35, desc: 'Badge of the plumber crew' },
  { id: 'ammo', name: 'Blaster Ammo ×20', emoji: '🔫', price: 25, desc: 'Restock the Plumber Blaster' },
  { id: 'grenades', name: 'Wrench Grenades ×3', emoji: '💣', price: 40, desc: 'Arcade boom — pure fun' },
];

export const ACTIVITIES = {
  fish: {
    xp: 15,
    coins: 25,
    energy: -10,
    message: 'You caught a fish! 🐟',
    item: { id: 'fish', name: 'Fresh Fish', emoji: '🐟' },
  },
  chop: {
    xp: 12,
    coins: 20,
    energy: -8,
    message: 'You chopped some wood! 🪵',
    item: { id: 'wood', name: 'Oak Wood', emoji: '🪵' },
  },
  mine: {
    xp: 18,
    coins: 30,
    energy: -12,
    message: 'You found some ore! 💎',
    item: { id: 'ore', name: 'Crystal Ore', emoji: '💎' },
  },
  cafe: {
    xp: 5,
    coins: -10,
    energy: 25,
    message: 'You enjoyed a coffee! ☕',
    item: null,
  },
  park: {
    xp: 3,
    coins: 0,
    energy: 8,
    message: 'You relax in the peaceful park. 🌳',
    item: null,
  },
  fixpipe: {
    xp: 22,
    coins: 45,
    energy: -12,
    message: 'Pipe sealed tight! The crew would be proud. 🔧',
    item: { id: 'pipe-scrap', name: 'Pipe Scrap', emoji: '🔩' },
  },
  plumbhq: {
    xp: 5,
    coins: 0,
    energy: 0,
    message: 'Pipeworks HQ — home of Cozy Town’s finest plumbers!',
    item: null,
  },
};

export const AVATARS = ['😊', '😎', '🧑‍🔧', '👩‍🔧', '🧔', '🧒', '🦊', '🐱', '🐸', '🦉'];

export const INTERACT_RANGE = 5.5;

/** Cartoon weapons — for fun, not realism */
export const WEAPONS = {
  gun: {
    id: 'gun',
    name: 'Plumber Blaster',
    emoji: '🔫',
    cooldown: 0.18,
    speed: 42,
    lifetime: 1.2,
    damage: 1,
  },
  grenade: {
    id: 'grenade',
    name: 'Wrench Grenade',
    emoji: '💣',
    cooldown: 0.9,
    throwSpeed: 14,
    fuse: 1.35,
    radius: 5,
  },
};
