/** World units: 1 unit ≈ 1 meter */

export const WORLD = {
  size: 80,
  half: 40,
};

export const PLAYER_MAX_HP = 100;
export const NPC_MAX_HP = 60;
/** Arcade KO — a few blaster hits */
export const NPC_RESPAWN_MS = 8000;

export const BUILDINGS = [
  {
    id: 'cafe',
    name: 'Cozy Cafe',
    x: -18,
    z: -8,
    w: 6,
    d: 5,
    h: 4.2,
    color: '#8B5A2B',
    roof: '#5C3317',
    emoji: '☕',
    action: 'Enter Cafe',
    activity: 'cafe',
    enterable: true,
  },
  {
    id: 'shop',
    name: 'General Store',
    x: 20,
    z: 4,
    w: 7,
    d: 6,
    h: 4.5,
    color: '#E85D5D',
    roof: '#9B2C2C',
    emoji: '🏪',
    action: 'Enter Shop',
    activity: 'shop',
    enterable: true,
  },
  {
    id: 'park',
    name: 'Central Park',
    x: 0,
    z: -22,
    w: 14,
    d: 10,
    h: 0.4,
    color: '#3D9B6E',
    roof: '#2E7D4F',
    emoji: '🌳',
    action: 'Relax',
    activity: 'park',
    flat: true,
  },
  {
    id: 'townhall',
    name: 'Town Hall',
    x: 2,
    z: 12,
    w: 9,
    d: 7,
    h: 6,
    color: '#5BA3C9',
    roof: '#2C6B8A',
    emoji: '🏛️',
    action: 'Enter Hall',
    activity: 'townhall',
    enterable: true,
  },
  {
    id: 'dock',
    name: 'Fishing Dock',
    x: -28,
    z: 22,
    w: 8,
    d: 4,
    h: 1.2,
    color: '#6B8E9F',
    roof: '#4A6570',
    emoji: '🎣',
    action: 'Fish',
    activity: 'fish',
    flat: true,
  },
  {
    id: 'forest',
    name: 'Dark Forest',
    x: 26,
    z: -22,
    w: 10,
    d: 10,
    h: 0.3,
    color: '#1F5C2E',
    roof: '#163F20',
    emoji: '🌲',
    action: 'Chop Wood',
    activity: 'chop',
    flat: true,
  },
  {
    id: 'mine',
    name: 'Crystal Mine',
    x: 28,
    z: 24,
    w: 7,
    d: 6,
    h: 3.5,
    color: '#6B6B7A',
    roof: '#3F3F4A',
    emoji: '⛏️',
    action: 'Enter Mine',
    activity: 'mine',
    enterable: true,
  },
  {
    id: 'plumbhq',
    name: 'Pipeworks HQ',
    x: -12,
    z: 18,
    w: 8,
    d: 6,
    h: 4.8,
    color: '#4A6FA5',
    roof: '#2C4060',
    emoji: '🔧',
    action: 'Enter HQ',
    activity: 'plumbhq',
    enterable: true,
  },
  {
    id: 'emily-garden',
    name: "Emily's Garden",
    x: -8,
    z: -28,
    w: 12,
    d: 10,
    h: 0.35,
    color: '#5cb87a',
    roof: '#3d9b5c',
    emoji: '🌷',
    action: 'Visit Garden',
    activity: 'garden',
    flat: true,
  },
];

/**
 * Pokémon-style indoor rooms. Local coords: door/exit near +z, spawn just inside.
 */
export const INTERIORS = {
  cafe: {
    name: 'Cozy Cafe',
    emoji: '☕',
    w: 22,
    d: 18,
    floor: '#d4b896',
    wall: '#6b3f24',
    accent: '#c4783a',
    sky: '#f0e0c8',
    spawn: { x: 0, z: 5 },
    exitZ: 7.5,
    props: [
      { type: 'counter', x: 0, z: -3.5, w: 6, d: 1.2, h: 1.1, color: '#5c3a22' },
      { type: 'table', x: -4, z: 0, color: '#8B5A2B' },
      { type: 'table', x: 4, z: 0, color: '#8B5A2B' },
      { type: 'table', x: -3, z: 2.5, color: '#8B5A2B' },
      { type: 'plant', x: 5.5, z: -4 },
      { type: 'plant', x: -5.5, z: -4 },
      { type: 'rug', x: 0, z: 1, w: 4, d: 3, color: '#c45c5c' },
    ],
    interactables: [
      { id: 'cafe-counter', name: 'Coffee Counter', emoji: '☕', x: 0, z: -2.8, action: 'Buy Coffee', activity: 'cafe' },
    ],
  },
  shop: {
    name: 'General Store',
    emoji: '🏪',
    w: 22,
    d: 18,
    floor: '#c9b8a0',
    wall: '#a83c3c',
    accent: '#e85d5d',
    sky: '#f5d8d0',
    spawn: { x: 0, z: 5 },
    exitZ: 7.5,
    props: [
      { type: 'counter', x: 0, z: -4, w: 7, d: 1.4, h: 1.15, color: '#5a3a2a' },
      { type: 'shelf', x: -5.5, z: -1, h: 2.4 },
      { type: 'shelf', x: 5.5, z: -1, h: 2.4 },
      { type: 'shelf', x: -5.5, z: 2, h: 2.4 },
      { type: 'crate', x: 4, z: 2 },
      { type: 'crate', x: -3.5, z: 2.5 },
    ],
    interactables: [
      { id: 'shop-counter', name: 'Shop Counter', emoji: '🛒', x: 0, z: -3.2, action: 'Browse Shop', activity: 'shop' },
    ],
  },
  townhall: {
    name: 'Town Hall',
    emoji: '🏛️',
    w: 24,
    d: 20,
    floor: '#d8cfc0',
    wall: '#3d6f8c',
    accent: '#5BA3C9',
    sky: '#d8e8f5',
    spawn: { x: 0, z: 5.5 },
    exitZ: 8.5,
    props: [
      { type: 'counter', x: 0, z: -4.5, w: 5, d: 1.5, h: 1.2, color: '#4a3a28' },
      { type: 'pillar', x: -5, z: -2 },
      { type: 'pillar', x: 5, z: -2 },
      { type: 'rug', x: 0, z: 0, w: 5, d: 6, color: '#3d6f8c' },
      { type: 'plant', x: -6, z: 4 },
      { type: 'plant', x: 6, z: 4 },
    ],
    interactables: [
      { id: 'hall-desk', name: 'Quest Board', emoji: '📜', x: 0, z: -3.5, action: 'View Quests', activity: 'townhall' },
    ],
  },
  mine: {
    name: 'Crystal Mine',
    emoji: '⛏️',
    w: 22,
    d: 18,
    floor: '#4a4a55',
    wall: '#2a2a32',
    accent: '#7ec8e3',
    sky: '#2a3040',
    spawn: { x: 0, z: 5 },
    exitZ: 7.5,
    props: [
      { type: 'crystal', x: -3, z: -3 },
      { type: 'crystal', x: 3.5, z: -2 },
      { type: 'crystal', x: 0, z: -4 },
      { type: 'rock', x: -4, z: 1 },
      { type: 'rock', x: 4, z: 2 },
      { type: 'crate', x: -2, z: 2 },
    ],
    interactables: [
      { id: 'mine-vein', name: 'Crystal Vein', emoji: '💎', x: 0, z: -3.5, action: 'Mine Ore', activity: 'mine' },
    ],
  },
  plumbhq: {
    name: 'Pipeworks HQ',
    emoji: '🔧',
    w: 22,
    d: 18,
    floor: '#7a8fa8',
    wall: '#2C4060',
    accent: '#4A6FA5',
    sky: '#c5d4e8',
    spawn: { x: 0, z: 5 },
    exitZ: 7.5,
    props: [
      { type: 'counter', x: 0, z: -4, w: 6, d: 1.3, h: 1.1, color: '#3a4a5c' },
      { type: 'pipe', x: -5, z: -1 },
      { type: 'pipe', x: 5, z: 1 },
      { type: 'crate', x: -4, z: 2 },
      { type: 'crate', x: 4, z: 2.5 },
      { type: 'plant', x: -6, z: 4 },
    ],
    interactables: [
      {
        id: 'hq-desk',
        name: 'Crew Desk',
        emoji: '🔧',
        x: 0,
        z: -3.2,
        action: 'Crew Briefing',
        activity: 'plumbhq',
      },
    ],
  },
};

/** Town locals + the Greek plumber crew + Billy */
export const NPCS = [
  {
    id: 1,
    name: 'Mayor Jenkins',
    x: 4,
    z: 8,
    emoji: '👨‍💼',
    color: '#F5D76E',
    role: 'mayor',
    action: 'Talk',
    dialogue: "Welcome to Cozy Town! The plumber crew keeps our pipes flowing — go say hi at Pipeworks HQ!",
  },
  {
    id: 2,
    name: 'Cafe Owner Luna',
    x: -16,
    z: -6,
    emoji: '👩‍🍳',
    color: '#F8B4C4',
    role: 'cafe',
    action: 'Talk',
    dialogue: 'Fresh coffee restores energy. The sink was dripping until Sofia fixed it!',
  },
  {
    id: 3,
    name: 'Shop Keeper Sam',
    x: 18,
    z: 2,
    emoji: '🛍️',
    color: '#A8E6CF',
    role: 'shop',
    action: 'Talk',
    dialogue: 'I stock tools, snacks… and for fun, blasters and grenades. Don’t tell the mayor.',
  },
  {
    id: 4,
    name: 'Fisher Bob',
    x: -26,
    z: 20,
    emoji: '🎣',
    color: '#8EC5E8',
    role: 'fisher',
    action: 'Talk',
    dialogue: 'The fish are biting today! Watch the dock pipes — Dimitri patched one last week.',
  },
  {
    id: 5,
    name: 'Woodcutter Alice',
    x: 24,
    z: -20,
    emoji: '🪓',
    color: '#C4A484',
    role: 'wood',
    action: 'Talk',
    dialogue: 'Need lumber? The forest always has more trees. Tell Nico I said hi!',
  },
  {
    id: 6,
    name: 'Billy',
    x: -2,
    z: 4,
    emoji: '🧑',
    color: '#7ec8ff',
    role: 'billy',
    title: 'Town Legend',
    wheelchair: true,
    roamRadius: 7,
    walkSpeed: 1.05,
    action: 'Talk',
    dialogue:
      "Hey! I'm Billy. Wheels don't slow me down — I know every crack in this town's sidewalks.",
    dialogues: [
      "Hey! I'm Billy. Wheels don't slow me down around Cozy Town.",
      'Best racing line? Fountain → cafe → dock. Ask me anytime.',
      'The plumbers are good people. Tell Nico I still want that ramp at HQ!',
      "If you're blasting friends, aim fair — and help with the leaks too!",
      'I roll the square most days. Wave if you see the blue chair!',
    ],
  },
  {
    id: 7,
    name: 'Emily',
    x: -8,
    z: -26,
    emoji: '👩‍🌾',
    color: '#f9a8d4',
    role: 'gardener',
    title: 'Garden Keeper',
    roamRadius: 5,
    walkSpeed: 1.2,
    action: 'Talk',
    dialogue: "Hi! I'm Emily — pick any flowers or mushrooms you like. They grow back!",
    dialogues: [
      "Welcome to Emily's Garden! Pick flowers, mushrooms, and petals — they're for sharing.",
      'Everything you pick goes in your inventory. Come back later — they regrow!',
      'Billy says the blue flowers are lucky. I just think they smell nice.',
      'If the plumbers flood the park again… well, more water for the roses!',
    ],
  },
  // —— Plumber crew (roam + fix leaks) ——
  {
    id: 10,
    name: 'Nico “The Wrench”',
    x: -10,
    z: 16,
    emoji: '🧑‍🔧',
    color: '#5B8DEF',
    role: 'plumber',
    title: 'Crew Boss',
    roamRadius: 16,
    walkSpeed: 1.7,
    action: 'Talk',
    dialogue:
      'Kalimera! I’m Nico, boss of the plumber crew. Fix the leaking pipes around town — talk to the crew and use Fix Pipe at the leaks!',
    dialogues: [
      'Kalimera! I’m Nico, boss of the plumber crew.',
      'Leaks never stop — we fix, they return. Personal fixes count for YOUR quests!',
      'Need firepower? Sam sells a Plumber Blaster. Arcade rules — tag friends!',
      'A good plumber listens to the pipes… and never loses their wrench.',
      'I walk the whole town checking pressure — catch me when you can!',
    ],
  },
  {
    id: 11,
    name: 'Yiannis',
    x: 3,
    z: 1,
    emoji: '🧔',
    color: '#7EB6FF',
    role: 'plumber',
    title: 'Pipe Whisperer',
    roamRadius: 11,
    walkSpeed: 1.4,
    action: 'Talk',
    dialogue: 'This fountain spring is a drama queen. Stand close to the leak and hit Fix Pipe!',
    dialogues: [
      'Yiannis here — I talk to pipes. They talk back.',
      'Fountain leak keeps coming back. We fix it together.',
      'Pressure is poetry. Also, don’t grenade the main valve. Please.',
      'I patrol the square — if you miss me, wait by the fountain.',
    ],
  },
  {
    id: 12,
    name: 'Sofia',
    x: -14,
    z: -10,
    emoji: '👩‍🔧',
    color: '#FF9ECD',
    role: 'plumber',
    title: 'Junior Ace',
    roamRadius: 12,
    walkSpeed: 2.0,
    action: 'Talk',
    dialogue: 'Sofia! Cafe pipes are my beat. Grab a wrench energy and fix the leak by the kitchen wall.',
    dialogues: [
      'Hey! Sofia — junior ace of the crew.',
      'Cafe leak is behind Luna’s place. I’ll seal it if you’re busy!',
      'Coffee + plumbing = the Cozy Town dream.',
      'I’m usually jogging between the cafe and HQ — wave if you see me!',
    ],
  },
  {
    id: 13,
    name: 'Dimitri',
    x: -26,
    z: 18,
    emoji: '🔧',
    color: '#FFB347',
    role: 'plumber',
    title: 'Dock Specialist',
    roamRadius: 10,
    walkSpeed: 1.5,
    action: 'Talk',
    dialogue: 'Dimitri at your service! Dock pipes freeze, crack, then party. Fix the leak on the pier.',
    dialogues: [
      'Dimitri — dock pipes, storms, and snacks.',
      'Pier leak is right by the water. One Fix Pipe and we’re golden.',
      'Between you and me, the blaster is great for “persuading” stubborn valves. Wink.',
      'I stick near the waterfront. Salt air is good for the soul.',
    ],
  },
  {
    id: 14,
    name: 'Elena',
    x: -8,
    z: 20,
    emoji: '😎',
    color: '#C3A6FF',
    role: 'plumber',
    title: 'Demo & Drama',
    roamRadius: 14,
    walkSpeed: 1.85,
    action: 'Talk',
    dialogue: 'Elena. I handle “controlled demolitions”… I mean pressure releases. Wrench Grenades go boom, pipes go calm.',
    dialogues: [
      'Elena — demo specialist. Mostly jokes. Mostly.',
      'HQ side leak needs a hero. Fix Pipe, then maybe toss a grenade for fun.',
      'Look around with the right stick. Move on the left — like a normal controller!',
      'If I’m walking, I’m thinking. If I’m running, something exploded. Probably fine.',
    ],
  },
  {
    id: 15,
    name: 'Costa',
    x: 12,
    z: -6,
    emoji: '👷',
    color: '#4fd1c5',
    role: 'plumber',
    title: 'Valve Runner',
    roamRadius: 15,
    walkSpeed: 2.1,
    action: 'Talk',
    dialogue: 'Costa — I sprint to every valve before the grass gets soggy.',
    dialogues: [
      'Costa on the move! Valves wait for no one.',
      'If you see a new puddle, yell — I’ll roll out.',
      'Master Plumber quest? YOU have to fix four — not just watch us.',
      'Left stick move, right stick look. Classic.',
    ],
  },
  {
    id: 16,
    name: 'Maria',
    x: 8,
    z: 18,
    emoji: '👩‍🏭',
    color: '#f687b3',
    role: 'plumber',
    title: 'Seal Specialist',
    roamRadius: 13,
    walkSpeed: 1.55,
    action: 'Talk',
    dialogue: 'Maria here. Perfect seals, every time. Mostly.',
    dialogues: [
      'Maria — seals, gaskets, and good coffee.',
      'Leaks respawn. That’s job security, friend.',
      'Billy races me around the square. He usually wins.',
      'Fix four yourself for Master Plumber. We only help the town.',
    ],
  },
  {
    id: 17,
    name: 'Theo',
    x: -20,
    z: 6,
    emoji: '🧔‍♂️',
    color: '#68d391',
    role: 'plumber',
    title: 'Night Shift',
    roamRadius: 14,
    walkSpeed: 1.35,
    action: 'Talk',
    dialogue: 'Theo. Day or night, the pipes still leak.',
    dialogues: [
      'Theo — night shift energy, daytime hours. Don’t ask.',
      'I take the weird leaks near the forest edge.',
      'Blaster tag is fine. Just don’t shoot the main line.',
      'Catch me west of town — slow and steady.',
    ],
  },
  {
    id: 18,
    name: 'Katerina',
    x: 22,
    z: -8,
    emoji: '🧑‍🚒',
    color: '#fc8181',
    role: 'plumber',
    title: 'Emergency Patch',
    roamRadius: 15,
    walkSpeed: 1.95,
    action: 'Talk',
    dialogue: 'Katerina — emergency patch kit always ready!',
    dialogues: [
      'Katerina reporting! Got a leak? I’m already halfway there.',
      'Shop side pipes act up when Sam stockpiles soda.',
      'We fix the town. You fix for quest glory. Teamwork!',
      'See you on the east side of town.',
    ],
  },
];

/** Interactable leaking pipes — keep respawning forever */
export const PIPE_LEAKS = [
  {
    id: 'leak-fountain',
    name: 'Fountain Leak',
    x: 1.5,
    z: -1.5,
    emoji: '💧',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Yiannis is watching this one',
  },
  {
    id: 'leak-cafe',
    name: 'Cafe Pipe Leak',
    x: -15,
    z: -11,
    emoji: '🚰',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Sofia’s job site',
  },
  {
    id: 'leak-dock',
    name: 'Dock Pipe Crack',
    x: -24,
    z: 20,
    emoji: '💦',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Dimitri’s specialty',
  },
  {
    id: 'leak-hq',
    name: 'HQ Pressure Valve',
    x: -9,
    z: 21,
    emoji: '🔧',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Elena left tools here',
  },
  {
    id: 'leak-park',
    name: 'Park Sprinkler Break',
    x: -4,
    z: -18,
    emoji: '💧',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Costa’s sprint route',
  },
  {
    id: 'leak-shop',
    name: 'Store Side Main',
    x: 16,
    z: 7,
    emoji: '🚰',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Maria’s patch zone',
  },
  {
    id: 'leak-forest',
    name: 'Forest Feeder Pipe',
    x: 22,
    z: -16,
    emoji: '💦',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Theo’s quiet job',
  },
  {
    id: 'leak-mine',
    name: 'Mine Coolant Line',
    x: 25,
    z: 20,
    emoji: '🔧',
    action: 'Fix Pipe',
    activity: 'fixpipe',
    hint: 'Katerina’s emergency call',
  },
];

/** Seconds before a fixed leak reappears (randomized in systems) */
export const LEAK_RESPAWN_MIN = 22;
export const LEAK_RESPAWN_MAX = 48;
export const PERSONAL_FIXES_FOR_MASTER = 4;

export const QUESTS = [
  {
    id: 'first-steps',
    title: 'First Steps',
    description: 'Visit the Town Hall',
    reward: { coins: 50, xp: 20 },
    completeOn: 'townhall',
  },
  {
    id: 'coffee-break',
    title: 'Coffee Break',
    description: 'Buy coffee at the cafe',
    reward: { coins: 30, xp: 15 },
    completeOn: 'cafe',
  },
  {
    id: 'fishing-trip',
    title: 'Fishing Trip',
    description: 'Catch a fish at the dock',
    reward: { coins: 100, xp: 50 },
    completeOn: 'fish',
  },
  {
    id: 'lumberjack',
    title: 'Lumberjack',
    description: 'Chop wood in the Dark Forest',
    reward: { coins: 60, xp: 30 },
    completeOn: 'chop',
  },
  {
    id: 'deep-delve',
    title: 'Deep Delve',
    description: 'Mine ore at Crystal Mine',
    reward: { coins: 80, xp: 40 },
    completeOn: 'mine',
  },
  {
    id: 'meet-crew',
    title: 'Meet the Crew',
    description: 'Talk to Nico at Pipeworks HQ',
    reward: { coins: 40, xp: 25 },
    completeOn: 'talk-nico',
  },
  {
    id: 'pipe-rookie',
    title: 'Pipe Rookie',
    description: 'Personally fix any leaking pipe',
    reward: { coins: 70, xp: 35 },
    completeOn: 'fixpipe',
  },
  {
    id: 'master-plumber',
    title: 'Master Plumber',
    description: 'Personally fix 4 leaks (NPC fixes don’t count)',
    reward: { coins: 200, xp: 100 },
    completeOn: 'fixpipe-all',
  },
  {
    id: 'meet-billy',
    title: 'Roll With Billy',
    description: 'Talk to Billy in the town square',
    reward: { coins: 45, xp: 25 },
    completeOn: 'talk-billy',
  },
  {
    id: 'emilys-bouquet',
    title: "Emily's Bouquet",
    description: 'Pick 5 flowers or mushrooms from the ground',
    reward: { coins: 60, xp: 35 },
    completeOn: 'pickup-5',
  },
  {
    id: 'visit-garden',
    title: "Visit Emily's Garden",
    description: "Relax in Emily's Garden south of town",
    reward: { coins: 40, xp: 20 },
    completeOn: 'garden',
  },
];

export const SHOP_ITEMS = [
  { id: 'bait', name: 'Fishing Bait', emoji: '🪱', price: 15, desc: 'Slightly better fishing luck' },
  { id: 'axe', name: 'Sturdy Axe', emoji: '🪓', price: 40, desc: 'A trusty woodcutting tool' },
  { id: 'pick', name: 'Iron Pick', emoji: '⛏️', price: 50, desc: 'Mine faster… spiritually' },
  { id: 'snack', name: 'Trail Mix', emoji: '🥜', price: 12, desc: 'Restores 15 energy' },
  { id: 'hat', name: 'Cozy Cap', emoji: '🧢', price: 75, desc: 'Looking good in town' },
  { id: 'wrench', name: 'Golden Wrench', emoji: '🔧', price: 35, desc: 'Badge of the plumber crew' },
  { id: 'ammo', name: 'Blaster Ammo ×20', emoji: '🔫', price: 25, desc: 'Restock the Plumber Blaster' },
  { id: 'grenades', name: 'Wrench Grenades ×3', emoji: '💣', price: 40, desc: 'Arcade boom — pure fun' },
  { id: 'medkit', name: 'First Aid Kit', emoji: '❤️', price: 30, desc: 'Restore full health' },
];

export const ACTIVITIES = {
  fish: {
    xp: 15,
    coins: 25,
    energy: -10,
    message: 'You caught a fish! 🐟',
    item: { id: 'fish', name: 'Fresh Fish', emoji: '🐟' },
  },
  chop: {
    xp: 12,
    coins: 20,
    energy: -8,
    message: 'You chopped some wood! 🪵',
    item: { id: 'wood', name: 'Oak Wood', emoji: '🪵' },
  },
  mine: {
    xp: 18,
    coins: 30,
    energy: -12,
    message: 'You found some ore! 💎',
    item: { id: 'ore', name: 'Crystal Ore', emoji: '💎' },
  },
  cafe: {
    xp: 5,
    coins: -10,
    energy: 25,
    message: 'You enjoyed a coffee! ☕',
    item: null,
  },
  park: {
    xp: 3,
    coins: 0,
    energy: 8,
    message: 'You relax in the peaceful park. 🌳',
    item: null,
  },
  fixpipe: {
    xp: 22,
    coins: 45,
    energy: -12,
    message: 'Pipe sealed tight! The crew would be proud. 🔧',
    item: { id: 'pipe-scrap', name: 'Pipe Scrap', emoji: '🔩' },
  },
  plumbhq: {
    xp: 5,
    coins: 0,
    energy: 0,
    message: 'Pipeworks HQ — home of Cozy Town’s finest plumbers!',
    item: null,
  },
  garden: {
    xp: 6,
    coins: 0,
    energy: 12,
    message: "You breathe in Emily's garden — so peaceful. 🌷",
    item: null,
  },
};

/** Deterministic ground pickups (flowers, mushrooms, etc.) */
function seeded(i, salt = 0) {
  const n = Math.sin(i * 12.9898 + salt * 78.233) * 43758.5453;
  return n - Math.floor(n);
}

const PICKUP_KINDS = [
  { emoji: '🌸', name: 'Pink Blossom', coins: 4, xp: 2 },
  { emoji: '🌺', name: 'Hibiscus', coins: 5, xp: 2 },
  { emoji: '🌼', name: 'Daisy', coins: 3, xp: 2 },
  { emoji: '🌻', name: 'Sunflower', coins: 6, xp: 3 },
  { emoji: '🍄', name: 'Mushroom', coins: 5, xp: 3 },
  { emoji: '🌷', name: 'Tulip', coins: 5, xp: 2 },
  { emoji: '🌹', name: 'Rose', coins: 7, xp: 3 },
  { emoji: '🍀', name: 'Lucky Clover', coins: 8, xp: 4 },
];

/** Build stable world pickup list once */
export const GROUND_PICKUPS = (() => {
  const list = [];
  // Town scatter
  for (let i = 0; i < 36; i++) {
    const kind = PICKUP_KINDS[i % PICKUP_KINDS.length];
    const a = seeded(i, 1) * Math.PI * 2;
    const r = 6 + seeded(i, 2) * 28;
    let x = Math.cos(a) * r;
    let z = Math.sin(a) * r;
    // keep off roads & water a bit
    if (Math.abs(x) < 2.2) x += x < 0 ? -3 : 3;
    if (Math.abs(z) < 2.2) z += z < 0 ? -3 : 3;
    if (x < -22 && z > 18) {
      x = -14;
      z = 10;
    }
    list.push({
      id: `town-${i}`,
      x,
      z,
      emoji: kind.emoji,
      name: kind.name,
      coins: kind.coins,
      xp: kind.xp,
      zone: 'town',
    });
  }
  // Emily's Garden dense patch (south of town)
  const gx = -8;
  const gz = -28;
  for (let i = 0; i < 28; i++) {
    const kind = PICKUP_KINDS[i % PICKUP_KINDS.length];
    const ox = (seeded(i, 7) - 0.5) * 10;
    const oz = (seeded(i, 9) - 0.5) * 8;
    list.push({
      id: `garden-${i}`,
      x: gx + ox,
      z: gz + oz,
      emoji: kind.emoji,
      name: kind.name,
      coins: kind.coins + 1,
      xp: kind.xp + 1,
      zone: 'garden',
    });
  }
  return list;
})();

/** Seconds before a picked flower regrows */
export const PICKUP_RESPAWN_MIN = 35;
export const PICKUP_RESPAWN_MAX = 90;

export const AVATARS = ['😊', '😎', '🧑‍🔧', '👩‍🔧', '🧔', '🧒', '🦊', '🐱', '🐸', '🦉'];

export const INTERACT_RANGE = 5.5;
export const INTERIOR_INTERACT_RANGE = 2.8;

/** Cartoon weapons — arcade damage, Minecraft-ish multi-hit KO */
export const WEAPONS = {
  gun: {
    id: 'gun',
    name: 'Plumber Blaster',
    emoji: '🔫',
    cooldown: 0.18,
    speed: 42,
    lifetime: 1.2,
    damage: 28,
    hitRadius: 1.35,
  },
  grenade: {
    id: 'grenade',
    name: 'Wrench Grenade',
    emoji: '💣',
    cooldown: 0.9,
    throwSpeed: 14,
    fuse: 1.35,
    radius: 5,
    damage: 55,
  },
};
