# Jekyll configuration for GitHub Pages
title: Cozy Town
description: A delightful mobile web game featuring Greek plumbers
baseurl: ""
url: "https://robdon3.github.io"

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .gitignore
  - README.md
  - DEPLOYMENT.md
  - .github/ 